//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string A = "a";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "AssetObj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "AssetObj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "AssetObj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "AssetObj";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string B = "b";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string C = "c";
    }
    public class Dog01_prefab
    {
        public const string BundleName = "dog01_prefab";
        public const string DOG01 = "Dog01";
    }
    public class Enemybar_prefab
    {
        public const string BundleName = "enemybar_prefab";
        public const string ENEMYBAR = "EnemyBar";
    }
    public class Fatknight_prefab
    {
        public const string BundleName = "fatknight_prefab";
        public const string FATKNIGHT = "FatKnight";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string IMAGEPREFABA = "ImagePrefabA";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string IMAGEPREFABB = "ImagePrefabB";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string IMAGEPREFABC = "ImagePrefabC";
    }
    public class Intention_attack_png
    {
        public const string BundleName = "intention_attack_png";
        public const string INTENTION_ATTACK = "Intention_Attack";
    }
    public class Intention_defense_png
    {
        public const string BundleName = "intention_defense_png";
        public const string INTENTION_DEFENSE = "Intention_Defense";
    }
    public class Intention_move_png
    {
        public const string BundleName = "intention_move_png";
        public const string INTENTION_MOVE = "Intention_Move";
    }
    public class Intention_ult_png
    {
        public const string BundleName = "intention_ult_png";
        public const string INTENTION_ULT = "Intention_Ult";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "SceneRes";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "TextureExample1";
    }
    public class Uibattlepanel_prefab
    {
        public const string BundleName = "uibattlepanel_prefab";
        public const string UIBATTLEPANEL = "UIBattlePanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPANELWITHIMAGEPREFAB = "UIPanelWithImagePrefab";
    }
    public class Uisettingpanel_prefab
    {
        public const string BundleName = "uisettingpanel_prefab";
        public const string UISETTINGPANEL = "UISettingPanel";
    }
    public class 血条信息_1_psb
    {
        public const string BundleName = "血条信息 1_psb";
        public const string 血条信息_1 = "血条信息 1";
    }
}
